name: CI

on: [push]

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    # Download and unzip linux repo of the current commit number of the submodule
    - name: Download and unzip linux repo
      run: |
        wget https://github.com/JaydenBBB/linux/archive/{$GITHUB_SHA}.zip
        unzip {$GITHUB_SHA}.zip
    - name: Build unzipped source code
      run: ./build-linux.sh linux-{$GITHUB_SHA} tinyconfig
