# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: 
      - main
    paths : 
      - linux/**
# A workflow run is made up of one or more jobs that can ut@v2run sequentially or in parallel
  # This workflow contains a single job called "build"
jobs:
  build:
    # The type of runner that the job will run on
  runs-on: ubuntu-20.04
    
    # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    - uses: actions/checkout@v2

    # Download and unzip linux repo of the current commit number of the submodule
    - name: Download and unzip linux repo
      run: |
        wget https://github.com/JaydenBBB/linux/archive/{$GITHUB_SHA}.zip
        unzip {$GITHUB_SHA}.zip
    - name: Build unzipped source code
      run: ./build-linux.sh linux-{$GITHUB_SHA} tinyconfig
