name: CI

on:
  push:
    branches:
      - 'main'
    #paths:
    #  - 'linux/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: johelegp/gcc-snapshot@v1 
      - uses: actions/checkout@v2

      # Download and unzip linux repo of the current commit number of the submodule
      - name: Download and unzip linux repo
        run: |
          var=$(git ls-tree main linux | awk '{ print $3 }')
          wget https://github.com/JaydenBBB/linux/archive/$var.zip
          unzip $var.zip
          ./build-linux.sh linux-$var tinyconfig
          
          # c
