name: CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'test'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 8
          platform: x64

      - uses: actions/checkout@v2

      # compile test cases
      - name: Download and unzip linux repo
        run: |
          make -C test
