name: CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'test/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # compile test cases
      - name: compile test cases
        run: |
          make -C test
